name: Run Python Server

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Input data'
        required: true
        default: ''

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python your_script.py ${{ github.event.inputs.data }}

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: path/to/results
