name: Deploy Flask Application

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Base64 encoded image'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        export FLASK_APP=app.py
        export FLASK_ENV=development
        nohup flask run --host=0.0.0.0 --port=5000 &

    - name: Test Flask endpoint
      run: |
        sleep 10  # Wait for the Flask app to start
        response=$(curl -X POST "http://localhost:5000/detect-passport" -H "Content-Type: application/json" -d "{\"image\": \"<base64-encoded-image-data>\"}")
        echo "Response: $response"
        echo "$response" > response.json

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: response
        path: response.json
