name: Run Jupyter Notebook with clean data

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter notebook pandas numpy fuzzywuzzy matplotlib tqdm tensorflow scikit-learn

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute recommend_clean_data.ipynb
        
    - name: Commit and push recommendation results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add user_place_recommendations_with_clean_data.csv
        git commit -m "Add recommendation results from Jupyter notebook clean data"
        git push
